# Generated by Django 4.1.6 on 2023-04-28 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='denumire')),
                ('description', models.TextField(verbose_name='text_articol')),
                ('date', models.DateTimeField(verbose_name='data_pub')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='autor')),
                ('commentary', models.CharField(max_length=150, verbose_name='text_commentariu')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.article')),
            ],
        ),
    ]
